version: "3"
services:
  database:
    image: mysql:8.0.33
    container_name: member_db
    environment:
      - MYSQL_DATABASE=member_db
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
      - TZ='Asia/Seoul'
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - member_network
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    links:
      - database
    ports:
      - 8081:8081
    container_name: member_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/member_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - member_network
#  redis:
#    image: redis:alpine
#    command: redis-server --port 6379
#    container_name: member_service_redis
#    hostname: member_service_redis
#    labels:
#      - "name=redis"
#      - "mode=standalone"
#    ports:
#      - 6379:6379

networks:
  member_network: