version: "3"
services:
  database:
    image: mysql
    container_name: member-service-db
    environment:
      - MYSQL_DATABASE=member-service-db
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - member-service-network
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/member-service-db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - member-service-network
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: member-service-redis
    hostname: member-service-redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379

networks:
  member-service-network: