server:
  port: 8080

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    encryptKey: k1m743hyun

management:
  endpoints:
    web:
      exposure:
        exclude:
          include: '*'
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    com.k1m743hyun.memberservice: DEBUG

spring:
  application:
    name: "member"
  datasource:
    url: ENC(ya2PRZWTJuDG2pp4XVT7APPaS4sP0IOKBt3NeIEZyay6tc5mTYppyfnX2OzoHMDJ8CGnzASNsSCgpS05JPOiOQ==)
    username: ENC(pzqMcuLassmcpZDDr2F8GE9H+EM/cX9O)
    password: ENC(pzqMcuLassmcpZDDr2F8GE9H+EM/cX9O)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  cloud:
    openfeign:
      client:
        config:
          order:
            url: "order:8080"
            logger-level: FULL