server:
  port: 8080

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    encryptKey: k1m743hyun

management:
  endpoints:
    web:
      exposure:
        exclude:
          include: '*'
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    com.k1m743hyun.memberservice: DEBUG

spring:
  application:
    name: "member"
  sql:
    init:
      mode: always
  datasource:
    url: ${MEMBER_DB_URL}
    username: ${MEMBER_DB_USERNAME}
    password: ${MEMBER_DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  cloud:
    openfeign:
      client:
        config:
          order:
            url: "order:8080"
            logger-level: FULL